//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: header.proto
namespace header
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Header")]
  public partial class Header : global::ProtoBuf.IExtensible
  {
    public Header() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _msgId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private int _userId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _errno;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"errno", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errno
    {
      get { return _errno; }
      set { _errno = value; }
    }
    private int _ext;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private byte[] _body = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] body
    {
      get { return _body; }
      set { _body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}