//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WndWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Wnd), typeof(System.Object));
		L.RegFunction("_Hide", _Hide);
		L.RegFunction("_Show", _Show);
		L.RegFunction("FindWidget", FindWidget);
		L.RegFunction("GetGameObject", GetGameObject);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateWnd);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("DefaultDuration", 0.5);
		L.RegVar("OnShowFinish", get_OnShowFinish, set_OnShowFinish);
		L.RegVar("OnDestroyFinish", get_OnDestroyFinish, set_OnDestroyFinish);
		L.RegVar("OnShowFinishEnd", get_OnShowFinishEnd, set_OnShowFinishEnd);
		L.RegVar("OnDestroyFinishEnd", get_OnDestroyFinishEnd, set_OnDestroyFinishEnd);
		L.RegVar("OnPreLoadFinish", get_OnPreLoadFinish, set_OnPreLoadFinish);
		L.RegVar("m_wndObj", get_m_wndObj, set_m_wndObj);
		L.RegVar("m_panelObj", get_m_panelObj, set_m_panelObj);
		L.RegVar("m_baffleObj", get_m_baffleObj, set_m_baffleObj);
		L.RegVar("Name", get_Name, null);
		L.RegVar("IsVisible", get_IsVisible, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWnd(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 1, typeof(UnityEngine.GameObject));
				UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
				wndInfo arg2 = (wndInfo)ToLua.CheckObject(L, 3, typeof(wndInfo));
				Wnd obj = new Wnd(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Wnd.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Hide(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Wnd obj = (Wnd)ToLua.CheckObject(L, 1, typeof(Wnd));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			WShowType arg1 = (WShowType)ToLua.CheckObject(L, 3, typeof(WShowType));
			obj._Hide(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Show(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Wnd obj = (Wnd)ToLua.CheckObject(L, 1, typeof(Wnd));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj._Show(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindWidget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Wnd obj = (Wnd)ToLua.CheckObject(L, 1, typeof(Wnd));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.FindWidget(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGameObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Wnd obj = (Wnd)ToLua.CheckObject(L, 1, typeof(Wnd));
			UnityEngine.GameObject o = obj.GetGameObject();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Wnd obj = (Wnd)ToLua.CheckObject(L, 1, typeof(Wnd));
			obj.Dispose();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnShowFinish(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Wnd.OnShowFinish);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnDestroyFinish(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Wnd.OnDestroyFinish);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnShowFinishEnd(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Wnd.OnShowFinishEnd);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnDestroyFinishEnd(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Wnd.OnDestroyFinishEnd);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnPreLoadFinish(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Wnd.OnPreLoadFinish);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_wndObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			UnityEngine.GameObject ret = obj.m_wndObj;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_wndObj on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_panelObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			UnityEngine.GameObject ret = obj.m_panelObj;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_panelObj on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_baffleObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			UnityEngine.GameObject ret = obj.m_baffleObj;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_baffleObj on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			string ret = obj.Name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Name on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsVisible(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			bool ret = obj.IsVisible;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsVisible on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnShowFinish(IntPtr L)
	{
		try
		{
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			Wnd.OnShowFinish = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnDestroyFinish(IntPtr L)
	{
		try
		{
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			Wnd.OnDestroyFinish = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnShowFinishEnd(IntPtr L)
	{
		try
		{
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			Wnd.OnShowFinishEnd = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnDestroyFinishEnd(IntPtr L)
	{
		try
		{
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			Wnd.OnDestroyFinishEnd = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnPreLoadFinish(IntPtr L)
	{
		try
		{
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			Wnd.OnPreLoadFinish = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_wndObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
			obj.m_wndObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_wndObj on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_panelObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
			obj.m_panelObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_panelObj on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_baffleObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Wnd obj = (Wnd)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
			obj.m_baffleObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_baffleObj on a nil value" : e.Message);
		}
	}
}

