//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MonoEX_Singleton_DP_CameraTrackObjectManageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MonoEX.Singleton<DP_CameraTrackObjectManage>), typeof(System.Object), "Singleton_DP_CameraTrackObjectManage");
		L.RegFunction("AutoInstance", AutoInstance);
		L.RegFunction("Release", Release);
		L.RegFunction("New", _CreateMonoEX_Singleton_DP_CameraTrackObjectManage);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Single", get_Single, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMonoEX_Singleton_DP_CameraTrackObjectManage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MonoEX.Singleton<DP_CameraTrackObjectManage> obj = new MonoEX.Singleton<DP_CameraTrackObjectManage>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MonoEX.Singleton<DP_CameraTrackObjectManage>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AutoInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MonoEX.Singleton<DP_CameraTrackObjectManage>.AutoInstance();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Release(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MonoEX.Singleton<DP_CameraTrackObjectManage>.Release();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Single(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, MonoEX.Singleton<DP_CameraTrackObjectManage>.Single);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

