//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIRect_AnchorUpdateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UIRect.AnchorUpdate));
		L.RegVar("OnEnable", get_OnEnable, null);
		L.RegVar("OnUpdate", get_OnUpdate, null);
		L.RegVar("OnStart", get_OnStart, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnEnable(IntPtr L)
	{
		ToLua.Push(L, UIRect.AnchorUpdate.OnEnable);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnUpdate(IntPtr L)
	{
		ToLua.Push(L, UIRect.AnchorUpdate.OnUpdate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnStart(IntPtr L)
	{
		ToLua.Push(L, UIRect.AnchorUpdate.OnStart);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UIRect.AnchorUpdate o = (UIRect.AnchorUpdate)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

