//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AvatarCMWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(AvatarCM));
		L.RegVar("Infantry_R", get_Infantry_R, null);
		L.RegVar("InfantryHero_R", get_InfantryHero_R, null);
		L.RegVar("Cavalry_R", get_Cavalry_R, null);
		L.RegVar("Cavalry_RH", get_Cavalry_RH, null);
		L.RegVar("CavalryHero_R", get_CavalryHero_R, null);
		L.RegVar("CavalryHero_RH", get_CavalryHero_RH, null);
		L.RegVar("Horse_H", get_Horse_H, null);
		L.RegVar("Cavalry_Fenshi", get_Cavalry_Fenshi, null);
		L.RegVar("Infantry_Fenshi", get_Infantry_Fenshi, null);
		L.RegVar("Max", get_Max, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Infantry_R(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Infantry_R);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InfantryHero_R(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.InfantryHero_R);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cavalry_R(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Cavalry_R);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cavalry_RH(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Cavalry_RH);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CavalryHero_R(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.CavalryHero_R);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CavalryHero_RH(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.CavalryHero_RH);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Horse_H(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Horse_H);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cavalry_Fenshi(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Cavalry_Fenshi);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Infantry_Fenshi(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Infantry_Fenshi);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Max(IntPtr L)
	{
		ToLua.Push(L, AvatarCM.Max);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		AvatarCM o = (AvatarCM)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

