//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FightParameterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FightParameter), typeof(System.Object));
		L.RegFunction("New", _CreateFightParameter);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Squares", get_Squares, set_Squares);
		L.RegVar("QixiSquare", get_QixiSquare, set_QixiSquare);
		L.RegVar("Music", get_Music, set_Music);
		L.RegVar("sceneID", get_sceneID, set_sceneID);
		L.RegVar("fightType", get_fightType, set_fightType);
		L.RegVar("tuiguan_zhang", get_tuiguan_zhang, set_tuiguan_zhang);
		L.RegVar("tuiguan_jie", get_tuiguan_jie, set_tuiguan_jie);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFightParameter(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FightParameter obj = new FightParameter();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FightParameter.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Squares(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			System.Collections.Generic.List<ArmySquareInfo> ret = obj.Squares;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Squares on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QixiSquare(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			ArmySquareInfo ret = obj.QixiSquare;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index QixiSquare on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Music(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			string ret = obj.Music;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Music on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sceneID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			int ret = obj.sceneID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index sceneID on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fightType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			FightType ret = obj.fightType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index fightType on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tuiguan_zhang(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			int ret = obj.tuiguan_zhang;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index tuiguan_zhang on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tuiguan_jie(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			int ret = obj.tuiguan_jie;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index tuiguan_jie on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Squares(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			System.Collections.Generic.List<ArmySquareInfo> arg0 = (System.Collections.Generic.List<ArmySquareInfo>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<ArmySquareInfo>));
			obj.Squares = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Squares on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_QixiSquare(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			ArmySquareInfo arg0 = (ArmySquareInfo)ToLua.CheckObject(L, 2, typeof(ArmySquareInfo));
			obj.QixiSquare = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index QixiSquare on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Music(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.Music = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Music on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sceneID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.sceneID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index sceneID on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_fightType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			FightType arg0 = (FightType)ToLua.CheckObject(L, 2, typeof(FightType));
			obj.fightType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index fightType on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_tuiguan_zhang(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.tuiguan_zhang = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index tuiguan_zhang on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_tuiguan_jie(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			FightParameter obj = (FightParameter)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.tuiguan_jie = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index tuiguan_jie on a nil value" : e.Message);
		}
	}
}

