//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FightManager_MemberTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FightManager.MemberType));
		L.RegVar("Base", get_Base, null);
		L.RegVar("Turret", get_Turret, null);
		L.RegVar("Soldier", get_Soldier, null);
		L.RegVar("Tank", get_Tank, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Base(IntPtr L)
	{
		ToLua.Push(L, FightManager.MemberType.Base);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Turret(IntPtr L)
	{
		ToLua.Push(L, FightManager.MemberType.Turret);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Soldier(IntPtr L)
	{
		ToLua.Push(L, FightManager.MemberType.Soldier);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Tank(IntPtr L)
	{
		ToLua.Push(L, FightManager.MemberType.Tank);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FightManager.MemberType o = (FightManager.MemberType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

