//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PacketRoutingWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PacketRouting), typeof(System.Object));
		L.RegFunction("Add", Add);
		L.RegFunction("Load", Load);
		L.RegFunction("LoadBytes", LoadBytes);
		L.RegFunction("LoadString", LoadString);
		L.RegFunction("UnLoad", UnLoad);
		L.RegFunction("New", _CreatePacketRouting);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePacketRouting(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				PacketRouting obj = new PacketRouting();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: PacketRouting.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Add(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PacketRouting obj = (PacketRouting)ToLua.CheckObject(L, 1, typeof(PacketRouting));
			IPacket arg0 = (IPacket)ToLua.CheckObject(L, 2, typeof(IPacket));
			obj.Add(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PacketRouting obj = (PacketRouting)ToLua.CheckObject(L, 1, typeof(PacketRouting));
			string arg0 = ToLua.CheckString(L, 2);
			FileSystem.RES_LOCATION arg1 = (FileSystem.RES_LOCATION)ToLua.CheckObject(L, 3, typeof(FileSystem.RES_LOCATION));
			UnityEngine.Object o = obj.Load(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadBytes(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PacketRouting obj = (PacketRouting)ToLua.CheckObject(L, 1, typeof(PacketRouting));
			string arg0 = ToLua.CheckString(L, 2);
			FileSystem.RES_LOCATION arg1 = (FileSystem.RES_LOCATION)ToLua.CheckObject(L, 3, typeof(FileSystem.RES_LOCATION));
			byte[] o = obj.LoadBytes(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			PacketRouting obj = (PacketRouting)ToLua.CheckObject(L, 1, typeof(PacketRouting));
			string arg0 = ToLua.CheckString(L, 2);
			FileSystem.RES_LOCATION arg1 = (FileSystem.RES_LOCATION)ToLua.CheckObject(L, 3, typeof(FileSystem.RES_LOCATION));
			string o = obj.LoadString(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnLoad(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PacketRouting obj = (PacketRouting)ToLua.CheckObject(L, 1, typeof(PacketRouting));
			obj.UnLoad();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

