//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIInput_InputTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UIInput.InputType));
		L.RegVar("Standard", get_Standard, null);
		L.RegVar("AutoCorrect", get_AutoCorrect, null);
		L.RegVar("Password", get_Password, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Standard(IntPtr L)
	{
		ToLua.Push(L, UIInput.InputType.Standard);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AutoCorrect(IntPtr L)
	{
		ToLua.Push(L, UIInput.InputType.AutoCorrect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Password(IntPtr L)
	{
		ToLua.Push(L, UIInput.InputType.Password);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UIInput.InputType o = (UIInput.InputType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

