-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('chat_pb')


CHATRECORD = protobuf.Descriptor();
local CHATRECORD_RID_FIELD = protobuf.FieldDescriptor();
local CHATRECORD_USERNAME_FIELD = protobuf.FieldDescriptor();
local CHATRECORD_CONTENT_FIELD = protobuf.FieldDescriptor();
local CHATRECORD_TIME_FIELD = protobuf.FieldDescriptor();
ENTERCHAT = protobuf.Descriptor();
local ENTERCHAT_TYPE_FIELD = protobuf.FieldDescriptor();
GETCHATRECORD = protobuf.Descriptor();
local GETCHATRECORD_TYPE_FIELD = protobuf.FieldDescriptor();
local GETCHATRECORD_TIME_FIELD = protobuf.FieldDescriptor();
GETCHATRECORDRESP = protobuf.Descriptor();
local GETCHATRECORDRESP_REC_FIELD = protobuf.FieldDescriptor();
CHATTOWORLD = protobuf.Descriptor();
local CHATTOWORLD_CONTENT_FIELD = protobuf.FieldDescriptor();
CHATTOWORLDNOTIFY = protobuf.Descriptor();
local CHATTOWORLDNOTIFY_REC_FIELD = protobuf.FieldDescriptor();

CHATRECORD_RID_FIELD.name = "rId"
CHATRECORD_RID_FIELD.full_name = ".ChatRecord.rId"
CHATRECORD_RID_FIELD.number = 1
CHATRECORD_RID_FIELD.index = 0
CHATRECORD_RID_FIELD.label = 2
CHATRECORD_RID_FIELD.has_default_value = false
CHATRECORD_RID_FIELD.default_value = 0
CHATRECORD_RID_FIELD.type = 5
CHATRECORD_RID_FIELD.cpp_type = 1

CHATRECORD_USERNAME_FIELD.name = "userName"
CHATRECORD_USERNAME_FIELD.full_name = ".ChatRecord.userName"
CHATRECORD_USERNAME_FIELD.number = 2
CHATRECORD_USERNAME_FIELD.index = 1
CHATRECORD_USERNAME_FIELD.label = 3
CHATRECORD_USERNAME_FIELD.has_default_value = false
CHATRECORD_USERNAME_FIELD.default_value = {}
CHATRECORD_USERNAME_FIELD.type = 5
CHATRECORD_USERNAME_FIELD.cpp_type = 1

CHATRECORD_CONTENT_FIELD.name = "content"
CHATRECORD_CONTENT_FIELD.full_name = ".ChatRecord.content"
CHATRECORD_CONTENT_FIELD.number = 3
CHATRECORD_CONTENT_FIELD.index = 2
CHATRECORD_CONTENT_FIELD.label = 2
CHATRECORD_CONTENT_FIELD.has_default_value = false
CHATRECORD_CONTENT_FIELD.default_value = 0
CHATRECORD_CONTENT_FIELD.type = 5
CHATRECORD_CONTENT_FIELD.cpp_type = 1

CHATRECORD_TIME_FIELD.name = "time"
CHATRECORD_TIME_FIELD.full_name = ".ChatRecord.time"
CHATRECORD_TIME_FIELD.number = 4
CHATRECORD_TIME_FIELD.index = 3
CHATRECORD_TIME_FIELD.label = 2
CHATRECORD_TIME_FIELD.has_default_value = false
CHATRECORD_TIME_FIELD.default_value = 0
CHATRECORD_TIME_FIELD.type = 5
CHATRECORD_TIME_FIELD.cpp_type = 1

CHATRECORD.name = "ChatRecord"
CHATRECORD.full_name = ".ChatRecord"
CHATRECORD.nested_types = {}
CHATRECORD.enum_types = {}
CHATRECORD.fields = {CHATRECORD_RID_FIELD, CHATRECORD_USERNAME_FIELD, CHATRECORD_CONTENT_FIELD, CHATRECORD_TIME_FIELD}
CHATRECORD.is_extendable = false
CHATRECORD.extensions = {}
ENTERCHAT_TYPE_FIELD.name = "type"
ENTERCHAT_TYPE_FIELD.full_name = ".EnterChat.type"
ENTERCHAT_TYPE_FIELD.number = 1
ENTERCHAT_TYPE_FIELD.index = 0
ENTERCHAT_TYPE_FIELD.label = 2
ENTERCHAT_TYPE_FIELD.has_default_value = false
ENTERCHAT_TYPE_FIELD.default_value = 0
ENTERCHAT_TYPE_FIELD.type = 5
ENTERCHAT_TYPE_FIELD.cpp_type = 1

ENTERCHAT.name = "EnterChat"
ENTERCHAT.full_name = ".EnterChat"
ENTERCHAT.nested_types = {}
ENTERCHAT.enum_types = {}
ENTERCHAT.fields = {ENTERCHAT_TYPE_FIELD}
ENTERCHAT.is_extendable = false
ENTERCHAT.extensions = {}
GETCHATRECORD_TYPE_FIELD.name = "type"
GETCHATRECORD_TYPE_FIELD.full_name = ".GetChatRecord.type"
GETCHATRECORD_TYPE_FIELD.number = 1
GETCHATRECORD_TYPE_FIELD.index = 0
GETCHATRECORD_TYPE_FIELD.label = 2
GETCHATRECORD_TYPE_FIELD.has_default_value = false
GETCHATRECORD_TYPE_FIELD.default_value = 0
GETCHATRECORD_TYPE_FIELD.type = 5
GETCHATRECORD_TYPE_FIELD.cpp_type = 1

GETCHATRECORD_TIME_FIELD.name = "time"
GETCHATRECORD_TIME_FIELD.full_name = ".GetChatRecord.time"
GETCHATRECORD_TIME_FIELD.number = 2
GETCHATRECORD_TIME_FIELD.index = 1
GETCHATRECORD_TIME_FIELD.label = 2
GETCHATRECORD_TIME_FIELD.has_default_value = false
GETCHATRECORD_TIME_FIELD.default_value = 0
GETCHATRECORD_TIME_FIELD.type = 5
GETCHATRECORD_TIME_FIELD.cpp_type = 1

GETCHATRECORD.name = "GetChatRecord"
GETCHATRECORD.full_name = ".GetChatRecord"
GETCHATRECORD.nested_types = {}
GETCHATRECORD.enum_types = {}
GETCHATRECORD.fields = {GETCHATRECORD_TYPE_FIELD, GETCHATRECORD_TIME_FIELD}
GETCHATRECORD.is_extendable = false
GETCHATRECORD.extensions = {}
GETCHATRECORDRESP_REC_FIELD.name = "rec"
GETCHATRECORDRESP_REC_FIELD.full_name = ".GetChatRecordResp.rec"
GETCHATRECORDRESP_REC_FIELD.number = 1
GETCHATRECORDRESP_REC_FIELD.index = 0
GETCHATRECORDRESP_REC_FIELD.label = 3
GETCHATRECORDRESP_REC_FIELD.has_default_value = false
GETCHATRECORDRESP_REC_FIELD.default_value = {}
GETCHATRECORDRESP_REC_FIELD.message_type = CHATRECORD
GETCHATRECORDRESP_REC_FIELD.type = 11
GETCHATRECORDRESP_REC_FIELD.cpp_type = 10

GETCHATRECORDRESP.name = "GetChatRecordResp"
GETCHATRECORDRESP.full_name = ".GetChatRecordResp"
GETCHATRECORDRESP.nested_types = {}
GETCHATRECORDRESP.enum_types = {}
GETCHATRECORDRESP.fields = {GETCHATRECORDRESP_REC_FIELD}
GETCHATRECORDRESP.is_extendable = false
GETCHATRECORDRESP.extensions = {}
CHATTOWORLD_CONTENT_FIELD.name = "content"
CHATTOWORLD_CONTENT_FIELD.full_name = ".ChatToWorld.content"
CHATTOWORLD_CONTENT_FIELD.number = 1
CHATTOWORLD_CONTENT_FIELD.index = 0
CHATTOWORLD_CONTENT_FIELD.label = 2
CHATTOWORLD_CONTENT_FIELD.has_default_value = false
CHATTOWORLD_CONTENT_FIELD.default_value = ""
CHATTOWORLD_CONTENT_FIELD.type = 9
CHATTOWORLD_CONTENT_FIELD.cpp_type = 9

CHATTOWORLD.name = "ChatToWorld"
CHATTOWORLD.full_name = ".ChatToWorld"
CHATTOWORLD.nested_types = {}
CHATTOWORLD.enum_types = {}
CHATTOWORLD.fields = {CHATTOWORLD_CONTENT_FIELD}
CHATTOWORLD.is_extendable = false
CHATTOWORLD.extensions = {}
CHATTOWORLDNOTIFY_REC_FIELD.name = "rec"
CHATTOWORLDNOTIFY_REC_FIELD.full_name = ".ChatToWorldNotify.rec"
CHATTOWORLDNOTIFY_REC_FIELD.number = 1
CHATTOWORLDNOTIFY_REC_FIELD.index = 0
CHATTOWORLDNOTIFY_REC_FIELD.label = 2
CHATTOWORLDNOTIFY_REC_FIELD.has_default_value = false
CHATTOWORLDNOTIFY_REC_FIELD.default_value = nil
CHATTOWORLDNOTIFY_REC_FIELD.message_type = CHATRECORD
CHATTOWORLDNOTIFY_REC_FIELD.type = 11
CHATTOWORLDNOTIFY_REC_FIELD.cpp_type = 10

CHATTOWORLDNOTIFY.name = "ChatToWorldNotify"
CHATTOWORLDNOTIFY.full_name = ".ChatToWorldNotify"
CHATTOWORLDNOTIFY.nested_types = {}
CHATTOWORLDNOTIFY.enum_types = {}
CHATTOWORLDNOTIFY.fields = {CHATTOWORLDNOTIFY_REC_FIELD}
CHATTOWORLDNOTIFY.is_extendable = false
CHATTOWORLDNOTIFY.extensions = {}

ChatRecord = protobuf.Message(CHATRECORD)
ChatToWorld = protobuf.Message(CHATTOWORLD)
ChatToWorldNotify = protobuf.Message(CHATTOWORLDNOTIFY)
EnterChat = protobuf.Message(ENTERCHAT)
GetChatRecord = protobuf.Message(GETCHATRECORD)
GetChatRecordResp = protobuf.Message(GETCHATRECORDRESP)

